language: node_js
node_js:
  - 7
  - 6
script: npm run build-test && npm test
addons:
  apt:
    sources:
      - sourceline: deb http://ppa.launchpad.net/mikegedelman/leiningen-git-stable/ubuntu trusty main
        key_url: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB8D7F7791716C8A4
    packages:
      - leiningen
